---
title: "Notes on Probability Theory"
author: "loikein"
date: "2019-04-03"
slug: "notes-probability-theory"
tags: ["math","stat"]
output:
  blogdown::html_page:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE, tidy = FALSE, echo = TRUE, eval = FALSE)
```

I dropped this course.

## Literature

1. [Probability & Measure Theory](http://93.174.95.27/book/index.php?md5=4F6782B53B6396C81FF68A3279106592)
2. Probability Theory and Elements of Measure Theory (Bauer, H.)
3. [Probability and Measure](http://93.174.95.27/book/index.php?md5=CD96EC194D0DA18DE6BE8ADA770E755A)
4. [Probability Theory: Independence, Interchangeability, Martingales](http://93.174.95.27/book/index.php?md5=D02302BD293B5CB1EB410DB892B2AE11) ★ measure
5. [A Course in Probability Theory](http://93.174.95.27/book/index.php?md5=1EC33C81975E516DD15B89F3B371A68F)
6. [Real Analysis and Probability](http://93.174.95.27/book/index.php?md5=4FF793A06AD870677D72048C1991007F)
7. [Probability: theory and examples](http://93.174.95.27/book/index.php?md5=FF89DA49E1912593C8C03134CE3E2964)
8. [An Introduction to Probability Theory and Its Applications, Vol 1](http://93.174.95.27/book/index.php?md5=3EDB18869B6F4EBFDA4E3FDA340C2952)  
[An Introduction to Probability Theory and Its Applications, Vol 2](http://93.174.95.27/book/index.php?md5=5212ABB6938A6997C82D2578B347D222) 
9. [Probability and Random Processes](http://93.174.95.27/book/index.php?md5=6275DDA19DF9420CE75DF73179373ACD)
10. [Probability essentials](http://93.174.95.27/book/index.php?md5=355BB740EEC2E4D0E359FC6CA5B61B4A)
11. [Foundations of the Theory of Probability](http://93.174.95.27/book/index.php?md5=EA1C2FA08729ACEB22A2470CA9B1D3A4) 
12. [Theory of probability and random processes](http://93.174.95.27/book/index.php?md5=0AB14C456F028A3BDB350119B51BD1E7)
13. [A Probability Path](http://93.174.95.27/book/index.php?md5=57B0DB931A9C16CE78078E90CE255244)  
[A probability path - Solution Manual](http://93.174.95.27/book/index.php?md5=A86D30A53A7484125781E3A3EC266C4D)
14. [Probability](http://93.174.95.27/book/index.php?md5=6149DD924DAB69AB32ADBA6682ED558B)
15. [Mathematics of Probability](http://93.174.95.27/book/index.php?md5=24B24662B7B0F475569740834FF36A5C)
16. [Knowing the Odds: An Introduction to Probability](http://93.174.95.27/book/index.php?md5=E62685F87278E9077C10A61CCE830EB1)

### Personal Reference

[Algebra of sets \- Wikipedia](https://en.wikipedia.org/wiki/Algebra_of_sets)  
[测度论入门教材推荐](https://www.zhihu.com/question/50628809)  
[代数结构入门：群、环、域、向量空间 - Spark & Shine](http://sparkandshine.net/algebraic-structure-primer-group-ring-field-vector-space/#4)  

[Union of σ-algebras is a π-system?](https://math.stackexchange.com/questions/2042362/union-of-sigma-algebras-is-a-pi-system)  
[What is the difference between a Ring and an Algebra?](https://math.stackexchange.com/questions/380177/what-is-the-difference-between-a-ring-and-an-algebra)  

## Measure Theory

- Carrier set: $M = \mathbb{R}^n$
- For vectors $a=(a_1,\dots, a_n)$ and $b=(b_1,\dots, b_n) \in M$
    - $a\leq b \iff a_i\leq b_i$ for all $i$
    - $a<b \iff a_i< b_i$ for all $i$

|      | σ-algebra                                           | Algebra                                      | Ring                                                     | Dynkin System                                                |
| ---- | --------------------------------------------------- | -------------------------------------------- | -------------------------------------------------------- | ------------------------------------------------------------ |
| 1    | $M\in \mathcal{A}$                                  | $M \in \mathcal{A}$                          | $\emptyset \in \mathcal{R}$                              | $M\in\mathcal{D}$                                            |
| 2    | $A\in \mathcal{A}$ <br />$\implies A^c \in \mathcal{A}$ | $A\in \mathcal{A}$ <br />$\implies A^c \in \mathcal{A}$ | $A,B\in \mathcal{R}$ <br />$\implies A\cap B^c \in\mathcal{R}$ | $D_1\subset D_2\in \mathcal{D}$ <br />$\implies D_2\cap D_1^c\in\mathcal{D}$ |
| 3    | $A_i\in \mathcal{A}$ <br />$\implies \cup_{i=1}^{\infty} A_i \in \mathcal{A}​$ | $A_i\in \mathcal{A}$ <br />$\implies \cup_{i=1}^n A_i \in \mathcal{A}$ | $A,B\in \mathcal{R}$ <br />$\implies A\cup B^c \in\mathcal{R}$ | Disjoint $D_i\in\mathcal{D}$ <br />$\implies\cup_{i=1}^{\infty}D_i\in\mathcal{D}$ |

Note: $A^c = M\cap A^c$

### σ-algebra

> Definition 1.1  
> Let $\mathcal{A}$ be a collection of subsets of set $M$, $\mathcal{A}$ is called a σ-algebra on $M\iff$  
> A1: $M\in \mathcal{A}$  
> A2: $A\in \mathcal{A}\implies A^c \in \mathcal{A}$  
> A3: For every sequence $(A_1, A_2,\dots)$ of $A_i\in \mathcal{A}\implies \cup_{i=1}^{\infty} A_i \in \mathcal{A}$

> Remark 1.2  
> Let $\mathcal{A}$ be a σ-algebra, then  
> a) A3': For every sequence $(A_1, A_2,\dots)$ of $A_i\in \mathcal{A}\implies \cap_{i=1}^{\infty} A_i \in \mathcal{A}$  
> b) For finite many sets $A_1,\dots,A_n\in \mathcal{A}\implies\cup_{i=1}^n A_i \in \mathcal{A}$ and $\cap_{i=1}^n A_i \in \mathcal{A}$

1. A3'  
Let $A_i\in \mathcal{A}$  
(A2) $\implies A_i^c\in \mathcal{A}$  
(A3) $\implies \cup_{i=1}^{\infty} A_i^c \in \mathcal{A}$  
(A2) $\implies \big( \cup_{i=1}^{\infty} A_i^c \big) ^c = \cap_{i=1}^{\infty} A_i \in \mathcal{A}$
2.  
Let $A_n = A_{n+1} = A_{n+2} =\dots$  
(A3) $\implies \cup_{i=1}^n A_i \in \mathcal{A}$  
(A3') $\implies \cap_{i=1}^n A_i \in \mathcal{A}$

> Example 1.3 (Reference: [Wikipedia](https://en.wikipedia.org/wiki/Sigma-algebra?oldformat=true#Simple_set-based_examples))  
> a) Power set $\mathcal{P}(M)$ is a σ-algebra on $M$  
> b) Let $T\neq\emptyset$ be an arbitrary index set, let $\mathcal{A}_t$ be a σ-algebra on M for all $t\in T$, then $\cap_{t\in T}\mathcal{A}_t$ is a σ-algebra on $M$  
> c) $\{M,\emptyset\}$ is a σ-algebra on $M$  

2. 
    1. $M \in \mathcal{A}_t$ for all $t\in T$  
    $\implies M\in \cap_{t\in T}\mathcal{A}_t$
    2. Let $A\in \cap_{t\in T}\mathcal{A}_t$  
    $\implies A\in \mathcal{A}_t$ for all $t\in T$  
    $\implies A^c\in \mathcal{A}_t$ for all $t\in T$  
    $\implies A^c\in\cap_{t\in T}\mathcal{A}_t$
    3. Let $A_i\in \cap_{t\in T}\mathcal{A}_t$ for $i = 1,2,\dots$  
    $\implies A_i\in \mathcal{A}_t$ for all $t\in T$ and all $i = 1,2,\dots$  
    $\implies \cup_{i=1}^{\infty} A_i\in \mathcal{A}_t$ for all $t\in T$  
    $\implies \cup_{i=1}^{\infty} A_i\in \cap_{t\in T}\mathcal{A}_t$

> Theorem 1.4  
> Let $\mathcal{C}$ be a set of subsets of $M$  
> Then there is a unique smallest σ-algebra $σ(\mathcal{C})$ on $M$ s.t. $\mathcal{C}\subset σ(\mathcal{C})$  
> Smallest: for all σ-algebra $\mathcal{A}$ on $M$ s.t. $\mathcal{C}\subset \mathcal{A}\implies σ(\mathcal{C})\subset \mathcal{A}$  
>   
> Definition 1.5  
> $σ(\mathcal{C})$ is called the σ-algebra on $M$  generated by $\mathcal{C}$  
> $\mathcal{C}$ is called a generator of $σ(\mathcal{C})$

1. Smallest  
Let $Φ$ be a set of all σ-algebras on $M$ that includes $\mathcal{C}$  
$\mathcal{P}(M)\in Φ\implies Φ\neq \emptyset$  
Let $σ(\mathcal{C}):= \cap_{\mathcal{A}\in Φ}\mathcal{A}$  
(Example 1.3.b) $\implies σ(\mathcal{C})$ is a σ-algebra on $M$  
Since $\mathcal{C}\subset \mathcal{A}$ for all $\mathcal{A}\in Φ$  
$\implies\mathcal{C}\subset σ(\mathcal{C})$  
(Def of $Φ$) $\implies σ(\mathcal{C})$ is a smallest σ-algebra on $M$
2. Unique  
Let $\mathcal{A}'$ be another smallest σ-algebra on $M$  
$\implies \mathcal{A}'\subset σ(\mathcal{C})$ and $σ(\mathcal{C})\subset \mathcal{A}'$  
$\implies \mathcal{A}' = σ(\mathcal{C})$

### Ring

> Definition 1.6  
> Let $\mathcal{R}$ be a set of subsets of a set $M$, $\mathcal{R}$ is called a ring on $M\iff$  
> R1: $\emptyset \in \mathcal{R}$  
> R2: $A,B\in \mathcal{R}\implies A\cap B^c \in\mathcal{R}$  
> R3: $A,B\in \mathcal{R}\implies A\cup B^c \in\mathcal{R}$  
>  
> If in addition,  
> R4: $M\in\mathcal{R}$  
> Then $\mathcal{R}$ is an __algebra__ on $M$

> Remark 1.7  
> a) $\mathcal{R}=\{\emptyset\}$ is a ring, but not an algebra on $M$ unless $M =\emptyset$  
> b) Set $\mathcal{A}\in\mathcal{P}(M)$ is called an algebra on $M\iff$  
> A1: $M\in \mathcal{A}$  
> A2: $A\in \mathcal{A}\implies A^c \in \mathcal{A}$  
> A3'': For finite many sets $A_1, A_2,\dots,A_n\in \mathcal{A} \implies \cup_{i=1}^n A_i \in \mathcal{A}$  
> c) Every σ-algebra is an algebra, the converse is not true in general

3. Counterexample  
Let $M = \mathbb{N}$, let $\mathcal{A} = \{A\subset M : |A|<\infty$ or $|A^c|<\infty\}$  
$\mathcal{A}$ is an algebra but not a σ-algebra  
For example, let $A_i = \{ (2_i)_i\}$ for all $i\in\mathbb{N}$  
$\implies A_i \in\mathcal{A}$ all $i\in\mathbb{N}$  
But $\cup_{i=1}^{\infty} A_i \not\in\mathcal{A}$ since $\big|\cup_{i=1}^{\infty} A_i\big| = \infty$

> - Set of half-open intervals: $\mathcal{I}^n:= \{]a,b] : a,b\in M, \ a\leq b \}$
>    - Half-open interval: $]a,b] = \{x\in M : a<x\leq b\}$
> - Set of figures: $\mathcal{F}^n := \{F\subset \mathbb{R}^n :$ exists $r\in\mathbb{N}$, exists $I_1,\dots,I_r \in\mathcal{I}^n$ s.t. $F=\cup _{j=1}^r I_j \}$ 
>    - $\emptyset =]a,a] \in\mathcal{I}^n$
>    - $\mathcal{I}^n\subset \mathcal{F}^n$

> Lemma 1.8  
> a) $I_1,I_2\in \mathcal{I}^n\implies$ $\begin{cases}I_1\cap I_2\in \mathcal{I}^n \\ I_1\cap I_2^c\in \mathcal{F}^n\end{cases}$  
> b) $F\in \mathcal{F}^n\implies$ exists disjoint intervals $I_1,\dots, I_r\in \mathcal{I}^n$ for some $r\in\mathbb{N}$, s.t. $F= \cup_{j=1}^r I_j$  
> c) $F,G\in \mathcal{F}^n\implies F\cap G\in \mathcal{F}^n$

Proof: Exercise 3

> Theorem 1.9  
> $\mathcal{F}^n$ is a ring on $M$  
>   
> Remark 1.10  
> $\mathcal{F}^n$ is the ring on $M$ generated by $\mathcal{I}^n$

1. $\emptyset \in \mathcal{I}^n\subset \mathcal{F}^n$
2. Let $F = \cup_{i=1}^r I_i$, $G = \cup_{j=1}^s I_j'$, $I_i,I_j' \in \mathcal{I}^n$  
$$\begin{aligned}\implies F \cap G^c &= \big( \cup_{i=1}^r I_i\big)\cap\big( \cap_{j=1}^s I_j^{'c} \big) \\
&=\cup_{i=1}^r \cap_{j=1}^s \big( I_i\cap I_j^{'c} \big)\end{aligned}$$ 
(Lemma 1.8.a) $\implies I_i\cap I_j^{'c} \in \mathcal{F}^n$  
(Lemma 1.8.c) $\implies \cap_{j=1}^s \big( I_i\cap I_j^{'c} \big)\in \mathcal{F}^n$  
(Def of $\mathcal{F}^n$) $\implies \cup_{i=1}^r \cap_{j=1}^s \big( I_i\cap I_j^{'c} \big)\in \mathcal{F}^n$
3. Trivial by definition of $\mathcal{F}^n$

### Dynkin System (λ-system)

> Definition 1.11  
> Let $\mathcal{D}$ be a collection of subsets of $M$. $\mathcal{D}$ is called a Dynkin system $\iff$  
> D1: $M\in\mathcal{D}$  
> D2: $D_1\subset D_2\in\mathcal{D}\implies$ $D_2\backslash D_1 = D_2\cap D_1^c\in\mathcal{D}$  
> D3: For every sequence $(D_1,D_2,\dots)$ of disjoint sets $D_i\in\mathcal{D}\implies \cup_{i=1}^{\infty}D_i\in\mathcal{D}$

> Remark 1.12  
> $\mathcal{A}$ is a σ-algebra $\implies\mathcal{A}$ is a Dynkin system, the converse is not true in general

Counterexample:  
Let $M=\{1,2,3,4\}$, $\mathcal{D} = \{ D\subset M : D$ has 0, 2 or 4 elements}  
Since union of sets of 2 elements may end up have 3 elements,  
$\implies \mathcal{D}$ is a Dynkin system but not a (σ-)algebra  

### π-system

> Definition 1.13.0  
> Let $\mathcal{C}$ be a collection of subsets of $M$. $\mathcal{C}$ is called a π-system  
> if for all $A_1, A_2\in\mathcal{C}\implies A_1\cap A_2\in\mathcal{C}$  
>   
> Lemma 1.13  
> Let $\mathcal{D}$ be a π-system and a Dynkin system on set $M$  
> $\implies\mathcal{D}$ is a σ-algebra on $M$

1. A1 $\iff$ D1
2. A2
3. A3

### Measures

> ES1.Exercise 2  
> Let $S$ be a finite set containing at least two elements.  
> Let $S^{\infty}$ be the set of all infinite sequences of elements of $S$.  
> For each $k\in\mathbb{N}$ and $ω\in S^{\infty}$ let $z_k(ω)$ be the $k$-th term of $ω$.  
> Then, $ω = \big( z_1(ω), z_2(ω),\dots\big)$.  
> A __cylinder of rank__ $n\in\mathbb{N}$ is a set of the form  
> $$\{ ω\in S^{\infty} : \big( z_1(ω), z_2(ω),\dots, z_n(ω)\big)\in H$$
> where $H\in S^n$. Let $\mathcal{C}$ be the set of all cylinders of all ranks.  
> a) Show that $S^{\infty}$ is uncountable.  
> b) 