---
title: "Notes on Industrial Organization"
author: "loikein"
date: "2019-10-07"
slug: "notes-industrial-organization"
tags: ["notes", "micro"]
output:
  blogdown::html_page:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE, tidy = FALSE, echo = TRUE, eval = FALSE)
```

## Basic Ideas

### Firm

- Firm: transforms inputs into outputs
- Profit: $Π = R(q) - C(q)$
- Sales: $q = f(k,l)$
- Cost: technology, expenditure minimization  
Let $q = \tilde{q}$, isovalue of production: $f(k,l) = \tilde{q}$  
Let $p_k$ be price of k, $p_l$ be price of l, given $E$, isovalue of expenditure: $k = -\frac{p_l}{p_k}\cdot l + \frac{E}{p_k}$  
Therefore, cost: $c(\tilde{q})=p_k\cdot\tilde{k} + p_l\cdot\tilde{l}$
- Revenue: demand, market interaction

### Consumer

- Income: $I$
- Demand: $Q(p)$
    - Individual demand: $Q_i(p_i, p_{-i}, T)$
    - Shift in $p_i$ moves along the curve, shift in other variables moves the curve
- Inverse demand: $P(q) = Q^{-1}(p)$

### Discrete Choice Model

- $M$ consumers, unit demand
- Willingness to pay: $v_i$ (known)
    - $v_1\geq v_2\geq\dots$
- Consumer's utility: $u_i(p)=\begin{cases}v_i-p &\text{buy} \\ 0 &\text{no buy}\end{cases}$
    - Buy $\iff v_i\geq p$
- Demand: $$Q(p) = \max_\{i \text{ s.t. } v_i\geq p\}$$
    - Decreasing in $p$

### Discrete Choice Model: Asymmetric Information

- cdf of $v$: $F(v)$
    - $v\in[\underline{v},\bar{v}]$
- Expected demand: $$\begin{aligned}Q(p) &= M\cdot Pr(v\geq p) \\ &= M\cdot\big(1-F(p)\big)\end{aligned}$$
    - Decreasing in $p$
    - When $F(v)$ is uniform, $Q(p)$ is linear

### Representative Consumer Model

- Identical consumers
- Consumer's utility: 
$$U(q_0, q_1,\dots, q_I) &= q_0 + u_1(q_1) + u_2(q_2) +\dots+u_I(q_I)$$
    - Goods: $i\in\{1,\dots, I\}$
    - Money left (Hicksian composite good): $q_0$, $p_0=1$
    - Concave utility function: $u_i$
- Each consumer's problem: 
$$\begin{aligned}\max_{q_i\geq 0} && &\phantom{\ggg}U(q_0, q_1,\dots, q_I)\\
&& &= q_0 + u_1(q_1) + u_2(q_2) +\dots+u_I(q_I) \\
\text{s.t.} && &q_0 + p_1q_1 + p_2q_2 + \dots + p_Iq_I \leq I\end{aligned}$$
Lagrangian:
$$\begin{aligned}\mathcal{L} &= q_0 + u_1(q_1) + u_2(q_2) +\dots+u_I(q_I)\\
&\phantom{\ggg}-λ(q_0 + p_1q_1 + p_2q_2 + \dots + p_Iq_I - I)\end{aligned}$$
FOC: $$\begin{aligned}\frac{\partial\mathcal{L}}{\partial q_0} &= 1-λ \overset{!}{=} 0\\
λ &= 1 \\
\frac{\partial\mathcal{L}}{\partial q_i} &= u_i'(q_i) - λ\cdot p_i \overset{!}{=} 0\\
u_i'(q_i) &= p_i \\
q_i &= (u_i')^{-1}(p_i) \\
p_i(q_i)&= u_i'(q_i)\end{aligned}$$
    - $q_i$ is increasing in $p_i$ if $u''<0$

### Welfare

- Partial equilibrium
    - Assume 1: change in $p_i$ does not affect $q_{-i}$
    - Assume 2: no serious substitution effects
- Measure
    - Firm: profit
    - Consumer: surplus (triangle)
    - Walfare = profit + consumer surplus
- Discrete choice: $u_i(p)=\begin{cases}v_i-p &\text{buy} \\ 0 &\text{no buy}\end{cases}$
$$\begin{aligned}CS &= \sum_{i=1}^m u_i(\tilde{p}) \\
&= \int_{\tilde{p}}^{\bar{p}} Q(p)\, dp\end{aligned}$$
- Representative consumer: $p_i(q_i)= u_i'(q_i)$
$$\begin{aligned}CS &= \int_{0}^{Q_i(\tilde{p}_i)} P(q_i) - \tilde{p}_i\, dq_i \\
&= \int_{0}^{Q_i(\tilde{p}_i)} u_i'(q_i) - \tilde{p}_i\, dq_i \\
&= \big[ u_i(q_i) - \tilde{p}_i\cdot q_i \big]_{0}^{Q_i(\tilde{p}_i)} \\
&= u_i\big(Q_i(\tilde{p}_i)\big) - \tilde{p}_i\cdot Q_i(\tilde{p}_i)\end{aligned}$$



