---
title: "Notes on Mechanism Design & Social Choice"
author: "loikein"
date: "2019-04-08"
slug: "notes-mechanism-social"
tags: ["notes", "micro", "GT"]
output:
  blogdown::html_page:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE, tidy = FALSE, echo = TRUE, eval = FALSE)
```

I dropped this course.

Textbook: (MWG) [Microeconomic Theory](http://93.174.95.27/book/index.php?md5=7C8A1C3D6A60923AC8D4BB873C31A24D) 

## Mechanism Design Problem

[Reference](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-254-game-theory-with-engineering-applications-spring-2010/lecture-notes/MIT6_254S10_lec20.pdf)

### Environment

- Set of agents: $i\in N = \{1,2,\dots, n\}$
- Set of possible alternatives: $x\in X$ 
    - $x$ is single-valued (MWG Definition 21.E.1)
- Type profile: $θ = (θ_1, θ_2,\dots, θ_n)\in Θ = Θ_1\times Θ_2\times\dots\times Θ_n$
    - pdf of $θ$ over $Θ$: $f$
    - Agent $i$'s type: $θ_i \in Θ_i$ 
- Agent $i$'s vNM utility function: $u_i(x,θ)$
    - ~~Allow for selflessness~~
    - Allow for reference
- Independent private values environment assumption
    - Private value: $u_i(x,θ) = u_i(x,θ_i)$
    - Independent type: $f_i(θ_i)$ s.t. $f(θ) = \prod_{i\in N} f_i(θ_i)$

### Mechanism

- Strategy profile: $s = (s_1, s_2,\dots, s_n)\in S = S_1\times S_2\times\dots\times S_n$
    - Agent $i$'s strategy: $s_i: Θ_i\to S_i$ for each $θ_i \in Θ_i$ 
- Outcome function: $g: S_1\times S_2\times\dots\times S_n\to X$
- Mechanism: $Γ = (S_1, S_2, \dots, S_n, g)$

### Induced Game

- Bayesian game induced by $Γ$:
$$G_Γ = [ \underbrace{N}_{\text{Players}}, \underbrace{\{S_i\}_{i\in N}}_{\text{Strategy}}, \underbrace{\{\tilde{u}_i\}_{i\in N}}_{\text{Payoff}}, \underbrace{Θ}_{\text{Type}}, \underbrace{f(\cdot)}_{\text{Probability}}]$$
    - Payoff function: $$\tilde{u}_i(s,θ) := u_i\big(\underbrace{g(s)}_{=x\in X},θ\big)$$
- Dominant strategy equilibrium: (MWG Definition 8.B.3)  
$s^*$ s.t. for all $i\in N$, for all $θ\in Θ$, for all $s_i'\in S_i$ and $s_{-i}\in S_{-i}$  
$$\tilde{u}_i\big(s^*_i(θ_i), s_{-i},θ\big)\geq \tilde{u}_i\big(s_i', s_{-i},θ\big)$$
- Bayesian Nash equilibrium: (MWG Proposition 8.E.1)  
$s^*$ s.t. for all $i\in N$, for all $θ_i\in Θ_i$, for all $s_i'\in S_i$  
$$E_{θ_{-i}}\Big[\tilde{u}_i\big(s^*_i(θ_i), s^*_{-i}(θ_{-i}),θ\big) \ \Big| \ θ_i\Big]\geq E_{θ_{-i}}\Big[\tilde{u}_i\big(s_i', s^*_{-i}(θ_{-i}),θ\big) \ \Big| \ θ_i\Big]$$

### Social Choice Function & Implementation

- SCF (Social Choice Function): $c: Θ\to X$
    - For all possible type profiles $θ$, assign $c(θ)\in X$ as the social choice
    - Ex post (Pareto) efficiency (MWG Definition 23.B.2)  
    $c$ is ex post efficient $\iff$ for all $θ$, exists no $x\in X$ s.t. 
    $$\begin{aligned}u_i(x,θ)\geq u_i\big(c(θ),θ\big) && \text{for all } i\in N \\
    u_i(x,θ)> u_i\big(c(θ),θ\big) && \text{for some } i\in N\end{aligned}$$
    - Implementable if exists a mechanism that implements it
    - Truthfully implementable (strategy-proof) if  
    it is the performance of an __incentive compatible + direct__ mechanism  
    or $Γ' = (Θ_1,\dots, Θ_n, c)$ is an incentive compatible mechanism
- $Γ$ implements $c$ / $c$ is a performance of $Γ$ (MWG Definition 23.B.4)  
if $G_Γ$ has an equilibrium $s^*$ s.t. $$\begin{aligned}g\big(s^*_1(θ_1), \dots, s^*_n(θ_n)\big) = c(θ) && \text{for all } θ\in Θ\end{aligned}$$
- $Γ$ is a direct (revelation) mechanism if (MWG Definition 23.B.5)  
    - All agents reveal types as action (not necessarily truthfully) $$\begin{aligned}S_i = Θ_i && \text{for all } i\in N\end{aligned}$$
    - Social choice made according to the self-reported types $$\begin{aligned}g(s) = g(θ) = c(θ) && \text{for all } θ\in Θ\end{aligned}$$
- Direct mechanism $Γ$ is incentive compatible if $s^*$ with $s^*_i(θ_i) = θ_i$ for all $θ_i\in Θ_i$, for all $i\in N$ is an equilibrium of $G_Γ$
- $Γ' = (Θ_1,\dots, Θ_n, c_Γ)$ is an incentive compatible mechanism for any $Γ$ with performance $c_Γ$

> Prove:  
> Revelation Principle (slide P38)  
> An SCE $c$ is implementable $\iff$ it is truthfully implementable

1. Dominant Strategy Equilibrium
2. Bayesian Nash Equilibrium

<!--
> Exercise  
> One seller, one buyer, one good  
> Seller has 0 value for the good (no production costs)  
> Buyer's willingness to pay is $θ\in [\underline{θ},\bar{θ}]$, $θ∼F$  
> Seller doesn't know $θ$  
> What's the best the seller can do?

1. Seller posts price $p$, buyer can accept or reject
2. Seller posts price $p_1$, if buyer rejects, seller posts price $p_2$
3. Buyer posts price $p$, seller can accept or reject
4. …

Mechanism: a game $Γ=(Σ_S, Σ_B, g)$  
$g: Σ_S\times Σ_B\to Δ \big( \{0,1\}\times\mathbb{R}\big)$  

1. Commitment to $Γ$
2. Seller commits to strategy $σ_S$

$\implies$ decision problem for the buyer  
$\implies$ involve revelation principle  
Buyer: for each $θ$ $\implies$ $σ^*_B(θ)$ $\implies$ $g\big(σ^*_B(θ) \big)$  
Direct mechanism: let $g^D(θ) = g\big(σ^*_B(θ) \big)$ s.t. $σ^D_B(θ) = θ$  

$DM = \{q(θ), t(θ)\}$  
where $q(θ)\in[0,1]$ is the probability of trade  
and $t(θ)$ is the payment made by the buyer  

Seller's problem: 
$$\begin{aligned}\max_{DM} && &E[t(θ)] \\
(IC) && θ\cdot q(θ) - t(θ)&\geq θ\cdot q(θ') - t(θ') && \text{for all } θ, θ' \\
(PC) && θ\cdot q(θ) - t(θ)&\geq 0 && \text{for all } θ \end{aligned}$$
(IC) $\implies$  
$$\begin{aligned} θ\cdot q(θ) - t(θ)&\geq θ\cdot q(θ') - t(θ') \\
θ'\cdot q(θ') - t(θ')&\geq θ'\cdot q(θ) - t(θ) \\
\implies (θ - θ')(q(θ) - q(θ')) &\geq 0\end{aligned}$$
if $θ>θ'\implies q(θ)>q(θ')$

Buyer's problem: 
$$\begin{aligned}U(θ) &= θq(θ) - t(θ) \\ &= \max_{θ'} \ θ\cdot q(θ') - t(θ')\end{aligned}$$
$\implies U$ is convex  
$U' = q(θ)\in [0,1]$  
$$\begin{aligned}q(θ) &= U'(θ) \\
t(θ) &= θq(θ) - U(θ)\end{aligned}$$ 

$\implies DM = \{q(θ), t(θ)\}$ is IC $\iff U$ is convex and $U\in [0,1]$  
$$\begin{aligned}U'(θ) &= q(θ) \\
U(θ) &= U(\underline{θ}) + \int_{\underline{θ}}^θ q(s) ds \\
E[t(θ)] &= \int_{\underline{θ}}^{\bar{θ}} t(θ) dF(θ) \\
&= \int_{\underline{θ}}^{\bar{θ}} θq(θ) - U(θ) dθ \\
&= \int_{\underline{θ}}^{\bar{θ}} \big[ θq(θ) - U(\underline{θ}) - \int_{\underline{θ}}^θ q(s) ds\big]dF(θ)\end{aligned}$$ 
Let $M = q(\cdot)$ weakly increasing and $q(\cdot)\in [0,1]$  
$$\begin{aligned}\max_{M} && &\phantom{\ggg}- U(\underline{θ}) + \int_{\underline{θ}}^{\bar{θ}} \big[ θq(θ)- \int_{\underline{θ}}^θ q(s) ds\big]dF(θ) \\
s.t. && &\phantom{\ggg}U(\underline{θ}) = 0 \\
\implies \max_{M} && &\phantom{\ggg}\int_{\underline{θ}}^{\bar{θ}} \big[ θq(θ)- \int_{\underline{θ}}^θ q(s) ds\big]dF(θ) \\
&& &= \int_{\underline{θ}}^{\bar{θ}} θq(θ)dF(θ)ds - \int_{\underline{θ}}^{\bar{θ}}\int_{\underline{θ}}^θ q(s) ds dF(θ) \\
&& &= \int_{\underline{θ}}^{\bar{θ}} θq(θ)dF(θ)ds - \int_{\underline{θ}}^{\bar{θ}} \big(\frac{1-F(θ}{q'(θ)}\big) q(θ) dF(θ) \\
&& &= \int_{\underline{θ}}^{\bar{θ}} q(θ)(θ- \frac{1-F(θ)}{q'(θ)})dF(θ) \end{aligned}$$

1. $M$ is convex and compact
2. object lives on $M$

$\implies$ optimizer is extreme point of $M$  
$\implies$ extreme points are $q(θ\in\{0,1\})$  
$\implies$ $θ^*$ s.t. $q(θ)=\begin{cases}1 & θ\geq θ^* \\ 0 & \text{else} \end{cases}$  
$\implies$ $t(θ)=\begin{cases} 0 & θ< θ^* \\ θ^* & θ\geq θ^* \end{cases}$

Seller's problem: 
$$\begin{aligned}\max_p && p\cdot(1-F(p))\end{aligned}$$
-->