---
title: "Introduction to JavaScript"
author: "loikein"
date: "2019-02-10"
slug: "intro-js"
tags: ["JavaScript","Programming"]
raw: ""
output:
  blogdown::html_page:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE, tidy = FALSE, echo = TRUE, eval = FALSE)
```

[19 个 JavaScript 有用的简写技术 \- SangSir \- SegmentFault 思否](https://segmentfault.com/a/1190000012673854)  
[表达式和运算符 \- JavaScript \| MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Expressions_and_Operators)

[理解 JavaScript 的 async/await \- 边城客栈 \- SegmentFault 思否](https://segmentfault.com/a/1190000007535316)  
[async 函数的含义和用法 \- 阮一峰的网络日志](http://www.ruanyifeng.com/blog/2015/05/async.html)

## Basics

````JavaScript
console.log( 'hello, world' );

// comment

/*
multi-line comment
*/

console.log( 22 + 3.5 );
console.log( 2019 - 1969 );
console.log( 65 / 240 );
console.log( 0.2708 * 100 );

console.log( 1 >= 2 );               // false
console.log( 3 <= 4 );               // true
console.log( 'orange' === 'apple' ); // false
console.log( 'orange' !== 'apple');  // true
````

### Constant

````JavaScript
const someConst = 'do not change';
someConst = 'hey';                   // Error!
````

### Variable

````JavaScript
var someNumber = 7;
var someString = 'what';

let someBoolean = true;
someBoolean = false;
console.log( someBoolean );          // false

// change type

let changeType = 'hey!';
console.log( typeof changeType);     // string

changeType = 1;
console.log( typeof changeType);     // number
````

### Assignment Operator

````JavaScript
let addMe = 95;
let subtractMe = 200;
let multiplyMe = 10;
let quarterMe = 400;

addMe += 5;                          // 100
subtractMe -= 100;                   // 100
multiplyMe *= 10;                    // 100
quarterMe /= 4;                      // 100
````

### Increment Operator

````JavaScript
let gainMe = 4;
let loseMe = 6;

gainMe ++;                           // 5
loseMe --;                           // 5
````

### String + Varible

````JavaScript
console.log( 'mind ' + 'the' + ' ' + 'gap' ); // mind the gap

let favoriteAnimal = 'panda';

console.log( 'My favorite animal: ' + favoriteAnimal ); // My favorite animal: panda
console.log( `My favorite animal: ${favoriteAnimal}` ); // My favorite animal: panda
````

### Property

````JavaScript
console.log( 'Count me'.length );
````

### Method

````JavaScript
console.log( 'hello'.toUpperCase() );            // HELLO

console.log( 'hello'.startsWith('a') );          // false

console.log('    Remove whitespace   '.trim() ); // Remove whitespace
````

## Built-in Object

### `Math`

````JavaScript
console.log( Math.random() );        // random number 0~1
console.log( Math.random() * 100 );

console.log( Math.floor( 43.8 ));    // 43
console.log( Math.ceil( 43.8 ));     // 44
````

### `Number`

````JavaScript
console.log(Number.isInteger( 2019 )); // true
````

## Conditional Statement

### `if`

```JavaScript
let sale = false;
let holiday = true;

if( sale && holiday ){
  console.log('Buy!');
} else {
  console.log( 'Wait for a sale.' );
}                                    // Wait for a sale.
```

### Truthy and Falsy

````JavaScript
let falsyNum = 0;
let falsyString = '';

if (falsyNum || falsyString) {
  console.log( true );
} else {
  console.log( false );
}                                    // false
````

### Short-Circuit Evaluation

````JavaScript
let userName = '';
let yourName = userName || 'Stranger';
console.log( yourName );             // Stranger

userName = 'rw';
let myName = userName || 'Stranger';
console.log( myName );               // rw
````

### Ternary Operator

````JavaScript
let answer = 99;
answer === 100 ?
  console.log('Correct') :
  console.log('Incorrect');          // Incorrect
````

### `else if`

````JavaScript
let season = 'summer';

if (season === 'spring') {
  console.log( 'It\'s spring' );
} else if (season === 'summer') {
  console.log( 'It\'s summer' );
} else if (season === 'fall') {
  console.log( 'It\'s fall' );
} else if (season === 'winter') {
  console.log( 'It\'s winter' );
} else {
  console.log( 'Invalid season.' );
}                                    // It's summer
````

### `switch`

````JavaScript
let season = 'summer';

switch( season ){
  case 'spring':
    console.log('It\'s spring');
    break;
  case 'summer':
    console.log( 'It\'s summer' );
    break;
  case 'fall':
    console.log( 'It\'s fall' );
    break;
  case 'winter':
    console.log( 'It\'s winter' );
    break;
  default:
    console.log( 'Invalid season.' );
    break;
}                                    // It's summer
````

## Function

````JavaScript
function hello(name = 'world' ){
  console.log( 'hello ' + name );
}
hello();                             // hello world
hello( 'rw' );                       // hello rw
````

````JavaScript
const hello = function( name = 'world' ){
  return( 'hello ' + name );
}

console.log( hello());               // hello world
console.log( hello( 'rw' ));         // hello rw
````

````JavaScript
function someFunctionWithAnnoyinglyLongName(){
  console.log( 'busy!' );
}

const busy = someFunctionWithAnnoyinglyLongName;
busy();                              // busy!
console.log( busy.name );            // someFunctionWithAnnoyinglyLongName
````

### Default Argument

````JavaScript
function makeShoppingList( item1 = 'milk', item2 = 'bread', item3 = 'eggs' ){
  console.log( `Remember to buy ${item1}` );
  console.log( `Remember to buy ${item2}` );
  console.log( `Remember to buy ${item3}` );
}
````

### Arrow Function

````JavaScript
const hello = ( name = 'world' ) => {
  return( 'hello ' + name );
}

console.log( hello());               // hello world
console.log( hello( 'rw' ));         // hello rw
````

````JavaScript
const hello = name => 'hello ' + name;

console.log( hello( 'world' ));      // hello world
console.log( hello( 'rw' ));         // hello rw
````

### Function in Function

````JavaScript
let price = 10;

function count( row, col ){
  return row * col;
}

function cost ( row, col ){
  return count( row, col ) * price;
}

console.log( cost( 5,4 ));           // 200
````

````JavaScript
function addFive( num ){
  return num + 5;
}

function checkTwice( func, arg ){
  let first = func( arg );
  let second = func( arg );
  if( first === second ){
    return 'Correct';
  } else {
    return 'Wrong';
  }
}

console.log( checkTwice( addFive, 2 ));          // Correct
````

## Scope

### Scope Pollution

````JavaScript
let someNumber = 1;

function change(){
  someNumber = 2;
  console.log( someNumber );
}

change();                            // 2
console.log( someNumber );           // 2
````

### Good Scoping

````JavaScript
let someNumber = 1;

function change(){
  let someNumber = 2;
  console.log( someNumber );
}

change();                            // 2
console.log( someNumber );           // 1
````

## Array

````JavaScript
let someArray = ['hello', 'there'];
let first = someArray[0];
console.log( first );                // hello
console.log( first[0] );             // h

someArray[0] = 'hallo';
console.log( someArray );            // [ 'hallo', 'there' ]

console.log( someArray.length );     // 2
````

### `let` & `const`

````JavaScript
let varArray = ['hello', 'there'];
const constArray = ['stay', 'hungry'];

varArray = 'hi';
console.log( varArray );             // hi

constArray = 'foolish';              // Error!

constArray[1] = 'foolish';
console.log( constArray );           // [ 'stay', 'foolish' ]
````

### Array Method

````JavaScript
const constArray = ['stay', 'hungry'];

constArray.push( 'stay', 'foolish' );
console.log( constArray );           // [ 'stay', 'hungry', 'stay', 'foolish' ]

constArray.pop();
console.log( constArray );           // [ 'stay', 'hungry', 'stay']

constArray.shift();
console.log( constArray );           // [ 'hungry', 'stay']

constArray.unshift("I'm");
console.log( constArray );           // [ 'I\'m', 'hungry', 'stay' ]

console.log( constArray.slice(0, 2) );           // [ 'I\'m', 'hungry' ]

constArray = ['stay', 'stay'];
console.log( constArray.indexOf( 'stay' ));      // 0
````

### Nested Array

````JavaScript
let moreArray = [ [1,2], [3,4], [5,6] ];

let six = moreArray[2][1];
console.log( six )                   // 6
````

## Loop

### `for`

````JavaScript
const someArray = [ 'stay', 'hungry', 'stay', 'foolish' ];

console.log( 'I want to' );
for( let i = 0; i < someArray.length; i++ ){
  console.log( someArray[i] );
}                                    // I want to stay hungry stay foolish
````

````JavaScript
const myFollowers = [ 'Lia', 'Susa', 'Cath', 'Dean' ];
const yourFollowers = [ 'Susa', 'Kate', 'Lia' ];
let mutualFollowers = [];

for( let i = 0; i < myFollowers.length; i++ ){
  for( let j = 0; j < yourFollowers.length; j++){
    if( myFollowers[i] === yourFollowers[j] ){
      mutualFollowers.push( myFollowers[i] );
    }
  }
}

console.log( mutualFollowers );      // [ 'Lia', 'Susa' ]
````

### `while`

````JavaScript
const someArray = [ 'stay', 'hungry', 'stay', 'foolish' ];

console.log( 'I want to' );

let i = 0;
while( i < someArray.length ){
  console.log( someArray[i] );
  i++;
}                                    // I want to stay hungry stay foolish
````

### `do ... while`

````JavaScript
const someArray = [ 'stay', 'hungry', 'stay', 'foolish' ];

console.log( 'I want to' );

let i = 0;
do {
  console.log( someArray[i] );
  i++;
} while( i < someArray.length );     // I want to stay hungry stay foolish
````

### `break`

````JavaScript
const someArray = [ 'stay', 'hungry', 'stay', 'foolish' ];

console.log( 'I want to' );

let i = 0;
do {
  console.log( someArray[i] );
  i++;
  if( someArray[i] === 'foolish' ){
    break;
  }
} while( i < someArray.length );     // I want to stay hungry stay
````

### Iteration

````JavaScript
const myFollowers = [ 'Lia', 'Susa', 'Cath', 'Dean' ];

myFollowers.forEach(
  follower => console.log( follower + ' is following me')
);

/*
Lia is following me
Susa is following me
Cath is following me
Dean is following me
*/

/* or
myFollowers.forEach(
  function( follower ){
    console.log( follower + ' is following me');
  }
); */
````

````JavaScript
const myFollowers = [ 'Lia', 'Susa', 'Cath', 'Dean' ];

console.log(
  myFollowers.map( follower => follower + ' is following me' )
);

/*
[ 'Lia is following me',
  'Susa is following me',
  'Cath is following me',
  'Dean is following me' ]
*/
````

````JavaScript
const myFollowers = [ 'Lia', 'Susa', 'Cath', 'Dean' ];

console.log(
  myFollowers.filter( follower => follower.length > 3 )
);

/*
[ 'Susa', 'Cath', 'Dean' ]
*/
````

````JavaScript
const myFollowers = [ 'Lia', 'Susa', 'Cath', 'Dean' ];

console.log(
  myFollowers.findIndex( follower => follower.length > 3 )
);

/*
1
*/
````

````JavaScript
const myFollowers = [ 'Lia', 'Susa', 'Cath', 'Dean' ];

const myFollowersList = myFollowers.reduce(
  ( list, nextName ) => list + ' ' + nextName
, 'My followers are');

console.log( myFollowersList );

/*
My followers are Lia Susa Cath Dean
*/
````

## Object

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
};

console.log( myComputer.color );     // black
console.log( myComputer['color'] );  // black
console.log( myComputer[ color ] );  // Error!

myComputer.numStickers = 3;

myComputer = { brand: 'ThinkPad', };

// delete myComputer.brand;
````

### Destructured Assignment

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
};

const { brand } = myComputer;
console.log( brand );                // Apple
````

### Method

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
  startUp(){ console.log( 'Duang!' )},
  // or: startUp: () => console.log( 'Duang!' ),
};

myComputer.startUp();                // Duang!
````

### Built-in Method

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
  startUp(){ console.log( 'Duang!' )},
};

console.log( Object.keys( myComputer ));
/*
[ 'brand', 'color', 'startUp' ]
*/

console.log( Object.entries( myComputer ));
/*
[ [ 'brand', 'Apple' ],
  [ 'color', 'black' ],
  [ 'startUp', [Function: startUp] ] ]
*/

let myNewComputer = Object.assign({ year: 2018 }, myComputer );
console.log( myNewComputer );
/*
{ year: 2018,
  brand: 'Apple',
  color: 'black',
  startUp: [Function: startUp] }
*/
````

### Nested Object

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
  startUp(){ console.log( 'Duang!' )},
  apps: {
    finder: { user: 'admin'},
    timeMachine: { user: 'all' },
  },
};

console.log( myComputer.apps.finder.user );      // admin
````

### Pass by Reference

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
};

function repaintFail( object ){
  object = { color: 'black', };
}

repaintFail( myComputer );
console.log( myComputer );

/*
{ brand: 'Apple',
  color: 'black' }
*/
````

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
};

function repaintSuccess( object ){
  object.color = 'silver';
}

repaintSuccess( myComputer );
console.log( myComputer );

/*
{ brand: 'Apple',
  color: 'silver' }
*/
````

### Loop in Object

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
  apps: {
    finder: { user: 'admin'},
    timeMachine: { user: 'all' },
  },
};

for( let app in myComputer.apps ){
  console.log( app + ' is used by ' + myComputer.apps[app].user );
}

/*
finder is used by admin
timeMachine is used by all
*/
````

### `this`

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
  claimFail: () => console.log( "I'm produced by " + this.brand ),
};

myComputer.claimFail();              // I'm produced by undefined
````

````JavaScript
const myComputer = {
  brand: 'Apple',
  color: 'black',
  claimSuccess(){ console.log( "I'm produced by " + this.brand )},
};

myComputer.claimSuccess();           // I'm produced by Apple
````

### `get`

````JavaScript
const myComputer = {
  _brand: 'Apple',
  _color: 'black',
  _battery: 50,
  get brand(){ return( "I'm produced by " + this._brand )},
  get battery(){ return( `${this._battery}% charged`)},
};

console.log( myComputer.brand);      // I'm produced by Apple
console.log( myComputer.battery);    // 50% charged
````

### `set`

````JavaScript
const myComputer = {
  _brand: 'Apple',
  _color: 'black',
  _battery: 50,
  get battery(){ return( `${this._battery}% charged` )},
  set battery( num ){ 
    if( typeof num === 'number' && num >= 0 ){
      this._battery = num;
    } else {
      console.log( 'Invalid battery status' );
    }
  }
};

myComputer.battery = 100;
console.log( myComputer.battery );   // 100% charged

myComputer.battery = 'charged';      // Invalid battery status
````

### Factory Function

````JavaScript
const computer = ( brand, color ) => {
  return{
    brand,
    color,
    startUp(){ console.log( 'Duang!' )}
  }
};

const myComputer = computer( 'Apple', 'black' );
myComputer.startUp();                // Duang!
````

## Class

````JavaScript
class Computer{
  constructor( brand, color ){
    this._brand = brand;
    this._color = color;
    this._battery = 50;
  }

  get brand(){ return this._brand }

  get color(){ return this._color }

  charge( batteryChange ){
    if( typeof batteryChange === 'number' && batteryChange >= 0 ){
      this._battery += batteryChange;
    } else {
      console.log( 'Invalid battery status' );
    }
  }
}

const myComputer = new Computer( 'Apple', 'black');
myComputer.charge( 50 );
console.log( myComputer._battery );              // 100
````

### Static Method

````JavaScript
class Computer{
  constructor( brand, color ){
    this._brand = brand;
    this._color = color;
    this._battery = 50;
  }

  get brand(){ return this._brand }

  get color(){ return this._color }

  charge( batteryChange ){
    if( typeof batteryChange === 'number' && batteryChange >= 0 ){
      this._battery += batteryChange;
    } else {
      console.log( 'Invalid battery status' );
    }
  }
  
  static generateSerial(){ return Math.floor( Math.random()*10000 )}
}

console.log( Computer.generateSerial );          // 2052 (changes every time)

const myComputer = new Computer( 'Apple', 'black');
console.log( myComputer.generateSerial );        // undefined
````

### Inheritance

````JavaScript
class Appliance{
  constructor( brand, color ){
    this._brand = brand;
    this._color = color;
    this._battery = 50;
  }
  get brand(){ return this._brand }
  get color(){ return this._color }
  charge( batteryChange ){
    if( typeof batteryChange === 'number' && batteryChange >= 0 ){
      this._battery += batteryChange;
    } else {
      console.log( 'Invalid battery status' );
    }
  }
}

class Computer extends Appliance{
  constructor( brand, color, apps ){
    super( brand, color );
    this._apps = apps;
  }
  installNewApp( appName ){
    this._apps.push( appName );
  }
}

const myComputer = new Computer( 'Apple', 'black', ['finder', 'timeMachine']);
myComputer.installNewApp( 'RStudio' );
console.log( myComputer );

/*
Computer {
  _brand: 'Apple',
  _color: 'black',
  _battery: 50,
  _apps: [ 'finder', 'timeMachine', 'RStudio' ] }
*/
````

## Module

### Create Module

1. Create an object
2. Add some properties
3. Export the object as a module

````JavaScript
const Computer = {
  brand: 'Apple',
  startUp(){ console.log( 'Duang!' )},
};

module.exports = Computer;

/*
or in ES6:
export default Computer;
*/
````

### Use Module

1. Import a module
2. Use properties of the module

````JavaScript
const Computer = require( './computer.js' );

/*
or in ES6:
import Computer from './computer';
*/

console.log( Computer.brand );                   // Apple
Computer.startUp();                              // Duang!
````

### Named Export & Import (ES6)

````JavaScript
const brand = 'Apple';
function startUp(){ console.log( 'Duang!' )};

export{ brand as computerBrand, startUp };

/*
or:
export const computerBrand = 'Apple';
export function startUp(){ console.log( 'Duang!' )};
*/
````

````JavaScript
import{ computerBrand, startUp as computerStartUp } from './computer';

console.log( computerBrand );                    // Apple
computerStartUp();                               // Duang!

/*
or:
import * as Computer from './computer';

console.log( Computer.computerBrand );           // Apple
Computer.startUp();                              // Duang!
*/
````

## Promise

````JavaScript
let someNumber = 7;

function executorFunction( resolve, reject ){
  if( someNumber > 5 ) {
      resolve( 'Greater than 5' );
  }else{
      reject( 'Smaller than 5' );
  }
}

const checkNumber = () => new Promise(executorFunction);

/*
or:
const checkNumber = () =>{
  return new Promise(
    function( resolve, reject ){
      if( someNumber > 5 ){ resolve( 'Greater than 5' ); }
      else{ reject( 'Smaller than 5' ); }
    }
)};
*/

console.log( checkNumber());                     // Greater than 5
````

### `setTimeout`

````JavaScript
console.log( 'The first line' );

function startUp(){
  console.log( 'Duang!' );
}

setTimeout( startUp, 1000 );

console.log( 'The last line' );

/*
The first line
The last line
Duang!
*/
````

### `then` & `catch`

````JavaScript
const checkNumber = ( num ) => {
  return new Promise(
    function( resolve, reject ){
      if( num > 5 ){ resolve( 'Greater than 5' ); }
      else{ reject( 'Smaller than 5' ); }
    }
)};

function onFulfilled( resolvedValue ){
  console.log( resolvedValue );
}

function onRejected( rejectionReason ){
  console.log( rejectionReason );
}

checkNumber( 7 ).then( onFulfilled, onRejected );
// Greater than 5

/*
don't do:

checkNumber( 7 ).then( onFulfilled )
                .then( onRejected );

// Greater than 5
// defined

do:

checkNumber( 7 ).then( onFulfilled )
                .catch( onRejected );

// Greater than 5
*/
````

### Multiple Promises (Composition)

````JavaScript
const checkNumber = ( num ) => {
  return new Promise(
    function( resolve, reject ){
      if( num > 5 ){ 
        console.log( 'Greater than 5' );
        resolve( num );
      }
      else{ reject( 'Smaller than 5' ); }
    }
)};

const checkNumberTwice = ( num ) => {
  return new Promise(
    function( resolve, reject ){
      if( num > 10 ){
        console.log( 'Greater than 10' );
        resolve( num );
      }
      else{ reject( 'Smaller than 10' ); }
    }
)};

checkNumber( 7 )
.then(( resolvedNumber ) =>
    { return checkNumberTwice( resolvedNumber ); })
.then(( successMessage ) =>
    { console.log( successMessage ); })
.catch(( errorMessage ) =>
    { console.log( errorMessage ); });

/*
Greater than 5
Smaller than 10
*/
````

### `Promise.all`

````JavaScript
const checkNumber = ( num ) => {
  return new Promise(
    function( resolve, reject ){
      if( num > 5 ){ 
        resolve( 'Greater than 5' );
      }
      else{ reject( 'Smaller than 5' ); }
    }
)};

const checkNumberTwice = ( num ) => {
  return new Promise(
    function( resolve, reject ){
      if( num > 10 ){
        resolve( 'Greater than 10' );
      }
      else{ reject( 'Smaller than 10' ); }
    }
)};

Promise.all([ checkNumber( 7 ),
              checkNumberTwice( 7 )])
.then(( successMessage ) =>
  { console.log( successMessage ); })
.catch(( errorMessage ) =>
  { console.log( errorMessage ); });

/*
Smaller than 10

// failing fast
*/
````

## Async Await

### `async`

````JavaScript
async function someFunc(){
  ...
}

//or

const someFunc = async () => {
  ...
}
````

````JavaScript
async function checkNumber( num ){
  if( num > 5 ){
    return( 'Greater than 5' );
  }else{
    return( 'Smaller than 5' );
  }
}

function onFulfilled( resolvedValue ){
  console.log( resolvedValue );
}

checkNumber( 7 )
.then( onFulfilled );      // Greater than 5

/*
or:
async function checkNumber( num ){
  if( num > 5 ){
    console.log( 'Greater than 5' );
  }else{
    console.log( 'Smaller than 5' );
  }
}
checkNumber( 7 );
*/
````

### `await`

````JavaScript
const chooseNumber = () => {
  return new Promise(
    function( resolve, reject ){
      setTimeout( () => {
        let number = Math.floor( Math.random() * 10 );
        console.log( number ); 
        resolve( number );
      }, 1000 )
    }
  )
};

async function checkNumber(){
  let num = await chooseNumber();
  if( num > 5 ){
    console.log( 'Greater than 5' );
    return( num );
  }else{
    console.log( 'Smaller than 5' );
    return( num );
  }
}

async function checkNumberTwice(){
  let num = await checkNumber();
  if( num > 10 ){
    console.log( 'Greater than 10' );
  }else{
    console.log( 'Smaller than 10' );
  }
}

checkNumberTwice();

/*
3
Smaller than 5
Smaller than 10
*/
````

### late await

````JavaScript
const chooseNumber = () => {
  return new Promise(
    function( resolve, reject ){
      setTimeout( () => {
        let number = Math.floor( Math.random() * 10 );
//      console.log( number ); 
        resolve( number );
      }, 1000 )
    }
  )
};

async function printNumber(){
  let num = chooseNumber();
  console.log( await num );
}

printNumber();               // 6
````

### `await Promise.all`

````JavaScript
const chooseNumber = () => {
  return new Promise(
    function( resolve, reject ){
      setTimeout( () => {
        let number = Math.floor( Math.random() * 10 );
        console.log( number ); 
        resolve( number );
      }, 1000 )
    }
  )
};

async function checkNumber(){
  let num = await chooseNumber();
  if( num > 5 ){
    console.log( 'Greater than 5' );
    return( num );
  }else{
    console.log( 'Smaller than 5' );
    return( num );
  }
}

async function checkNumberTwice(){
  let num = await Promise.all([ chooseNumber(), checkNumber() ]);
  if( num > 10 ){
    console.log( 'Greater than 10' );
  }else{
    console.log( 'Smaller than 10' );
  }
}

checkNumberTwice();

/*
3
Smaller than 5
Smaller than 10
*/
````

### `try ... catch`

````JavaScript
async function checkNumber( num ){
  try{
    if( num > 5 ){
      console.log( 'Greater than 5' );
    }else{
      console.log( 'Smaller than 5' );
    }
  } catch( error ) {
      console.log( error );
  }
}

checkNumber( 7 );            // Greater than 5
````

## Request

AJAX (Asynchronous JavaScript and XML)

### XHR GET

````JavaScript
const xhr = new XMLHttpRequest();
const url = 'http://api-to-call.com/endpoint';

xhr.responseType = 'json';

xhr.onreadystatechange = () => {
  if( xhr.readyState === XMLHttpRequest.DONE ){
    // response
    // return xhr.response;
  }
};

xhr.open( 'GET', url );
xhr.send();
````

### XHR POST

````JavaScript
const xhr = new XMLHttpRequest();
const url = 'http://api-to-call.com/endpoint';
const data = JSON.stringify({ id:'200' });

xhr.responseType = 'json';

xhr.onreadystatechange = () => {
  if( xhr.readyState === XMLHttpRequest.DONE ){
    // response
  }
};

xhr.open( 'POST', url );
xhr.send( data );
````

### Fetch GET

````JavaScript
fetch( 'http://api-to-call.com/endpoint' )
.then( response => {
  if( response.ok ){
    return response.json();
  }
  throw new Error( 'Request failed!' );
}, networkError => console.log( networkError.message ))
.then( jsonResponse => {
  // response
  // return jsonResponse;
});
````

### Fecth POST

````JavaScript
fetch( 'http://api-to-call.com/endpoint',
       { method: 'POST', body: JSON.stringify({id:'200'}) })
.then( response => {
  if( response.ok ){
    return response.json();
  }
  throw new Error( 'Request failed!' );
}, networkError => console.log( networkError.message ))
.then( jsonResponse => {
  // response
  // return jsonResponse;
});
````

### Async GET

````JavaScript
async function getData(){
  try{
    const response = await fetch( 'http://api-to-call.com/endpoint' );
    if( response.ok ){
      const jsonResponse = await response.json;
      // response
      // return jsonResponse;
    }
    throw new Error( 'Request failed!' );
  } catch( error ){
    console.log( error );
    // or: redirection
  }
}
````

### Async POST

````JavaScript
async function getData(){
  try{
    const response = await fetch( 'http://api-to-call.com/endpoint',
                                  { method: 'POST', body: JSON.stringify({id:'200'}) });
    if( response.ok ){
      const jsonResponse = await response.json;
      // response
      // return jsonResponse;
    }
    throw new Error( 'Request failed!' );
  } catch( error ){
    console.log( error );
    // or: redirection
  }
}
````

## Browser Compatibility

### Babel

````bash
$ ls
# src

$ npm init
# name: test-babel
# discription: Use Babel to transpile JavaScript ES6 to ES5
# this command will create a package.json file to prepare the project

$ ls
# package.json  src

$ npm install babel-cli -D
$ npm install babel-preset-env -D

$ ls
# node_modules  package.json  src

$ touch .babelrc
# add >{"presets": ["env"]}< in the .babelrc file

# add >"build": "babel src -d lib"< beneath "scripts": "test" in the package.json file

$ npm run build

# > test-babel@1.0.0 build /home/ccuser/workspace/learn-javascript-transpilation-bct-npm-init
# > babel src -d lib
# src/main.js -> lib/main.js
# (ES6)          (ES5)
````


